[package]
name = "biuwu"
version = "1.0.0"
authors = []

[addresses]
biuwu = "_"
test_coins = "0xfefe"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
